//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eidss.webclient.EhsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EhsService.IEhsFacade")]
    public interface IEhsFacade {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEhsFacade/ValidateData", ReplyAction="http://tempuri.org/IEhsFacade/ValidateDataResponse")]
        eidss.model.Model.UploadEhs.ValidateDataResult ValidateData(string patientJson, string eventJson, long idfsUploadEhs, string lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEhsFacade/SaveUploadedData", ReplyAction="http://tempuri.org/IEhsFacade/SaveUploadedDataResponse")]
        eidss.model.Model.UploadEhs.SaveDataResult SaveUploadedData(long idfsUploadEhs, long idfPersonEnteredBy, long idfUserID, string lang);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEhsFacadeChannel : eidss.webclient.EhsService.IEhsFacade, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EhsFacadeClient : System.ServiceModel.ClientBase<eidss.webclient.EhsService.IEhsFacade>, eidss.webclient.EhsService.IEhsFacade {
        
        public EhsFacadeClient() {
        }
        
        public EhsFacadeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EhsFacadeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EhsFacadeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EhsFacadeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public eidss.model.Model.UploadEhs.ValidateDataResult ValidateData(string patientJson, string eventJson, long idfsUploadEhs, string lang) {
            return base.Channel.ValidateData(patientJson, eventJson, idfsUploadEhs, lang);
        }
        
        public eidss.model.Model.UploadEhs.SaveDataResult SaveUploadedData(long idfsUploadEhs, long idfPersonEnteredBy, long idfUserID, string lang) {
            return base.Channel.SaveUploadedData(idfsUploadEhs, idfPersonEnteredBy, idfUserID, lang);
        }
    }
}
